import Head from "next/head";
import ListContainer from "../components/listContainer";
import TopBlog from "../components/upperBlog";
import mongoose from 'mongoose';
import Blog from '../models/Blog';

export default function Home({blogs}) {
  return (
    <div>
      <Head>
        <title>Expresso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <TopBlog data={blogs} />
      <ListContainer data = {blogs}/>
    </div>
  );
}

export async function getServerSideProps(context) {
  if(!mongoose.connections[0].readyState){
  

  await mongoose.connect(process.env.MONGO_URL)
  }
  let blogs = await Blog.find();
  return {
     
    props: {blogs:JSON.parse(JSON.stringify(blogs))},
  }
}
